use std::str::FromStr;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VtecPhenomenon {
    AshfallLand,
    AirStagnation,
    BeachHazard,
    BriskWind,
    Blizzard,
    CoastalFlood,
    DebrisFlow,
    DustStorm,
    BlowingDust,
    ExtremeCold,
    ExcessiveHeat,
    ExtremeWind,
    Flood,
    FlashFlood,
    DenseFogLand,
    FloodForecastPoints,
    Frost,
    FireWeather,
    Freeze,
    Gale,
    HurricaneForceWind,
    Heat,
    Hurricane,
    HighWind,
    Hydrologic,
    HardFreeze,
    IceStorm,
    LakeEffectSnow,
    LowWater,
    LakeshoreFlood,
    LakeWind,
    Marine,
    DenseFogMarine,
    AshfallMarine,
    DenseSmokeMarine,
    RipCurrentRisk,
    SmallCraft,
    HazardousSeas,
    DenseSmokeLand,
    Storm,
    StormSurge,
    SnowSquall,
    HighSurf,
    SevereThunderstorm,
    Tornado,
    TropicalStorm,
    Tsunami,
    Typhoon,
    HeavyFreezingSpray,
    WindChill,
    Wind,
    WinterStorm,
    WinterWeather,
    FreezingFog,
    FreezingRain,
    FreezingSpray,
}

impl FromStr for VtecPhenomenon {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(match s.to_ascii_lowercase().as_str() {
            "af" => Self::AshfallLand,
            "as" => Self::AirStagnation,
            "bh" => Self::BeachHazard,
            "bw" => Self::BriskWind,
            "bz" => Self::Blizzard,
            "cf" => Self::CoastalFlood,
            "df" => Self::DebrisFlow,
            "ds" => Self::DustStorm,
            "du" => Self::BlowingDust,
            "ec" => Self::ExtremeCold,
            "eh" => Self::ExcessiveHeat,
            "ew" => Self::ExtremeWind,
            "fa" => Self::Flood,
            "ff" => Self::FlashFlood,
            "fg" => Self::DenseFogLand,
            "fl" => Self::FloodForecastPoints,
            "fr" => Self::Frost,
            "fw" => Self::FireWeather,
            "fz" => Self::Freeze,
            "gl" => Self::Gale,
            "hf" => Self::HurricaneForceWind,
            "ht" => Self::Heat,
            "hu" => Self::Hurricane,
            "hw" => Self::HighWind,
            "hy" => Self::Hydrologic,
            "hz" => Self::HardFreeze,
            "is" => Self::IceStorm,
            "le" => Self::LakeEffectSnow,
            "lo" => Self::LowWater,
            "ls" => Self::LakeshoreFlood,
            "lw" => Self::LakeWind,
            "ma" => Self::Marine,
            "mf" => Self::DenseFogMarine,
            "mh" => Self::AshfallMarine,
            "ms" => Self::DenseSmokeMarine,
            "rp" => Self::RipCurrentRisk,
            "sc" => Self::SmallCraft,
            "se" => Self::HazardousSeas,
            "sm" => Self::DenseSmokeLand,
            "sr" => Self::Storm,
            "ss" => Self::StormSurge,
            "sq" => Self::SnowSquall,
            "su" => Self::HighSurf,
            "sv" => Self::SevereThunderstorm,
            "to" => Self::Tornado,
            "tr" => Self::TropicalStorm,
            "ts" => Self::Tsunami,
            "ty" => Self::Typhoon,
            "up" => Self::HeavyFreezingSpray,
            "wc" => Self::WindChill,
            "wi" => Self::Wind,
            "ws" => Self::WinterStorm,
            "ww" => Self::WinterWeather,
            "zf" => Self::FreezingFog,
            "zr" => Self::FreezingRain,
            "zy" => Self::FreezingSpray,

            _ => return Err(()),
        })
    }
}
