use crate::primary::significance::VtecSignificance;
use std::{
    fmt::{self, Display, Formatter},
    str::FromStr,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VtecPhenomenon {
    AirQuality,
    AirStagnation,
    BeachHazards,
    BriskWind,
    Blizzard,
    CoastalFlood,
    ColdWeather,
    DustStorm,
    BlowingDust,
    ExtremeCold,
    ExcessiveHeat,
    ExcessiveWind,
    ArealFlood,
    FlashFlood,
    DenseFog,
    Flood,
    Hydrological,
    Frost,
    FireWeather,
    RedFlag,
    Freeze,
    Gale,
    HurricaneForceWind,
    Heat,
    Hurricane,
    HighWind,
    SnowSquall,
    IceStorm,
    LakeEffectSnow,
    LowWater,
    LakeshoreFlood,
    LakeWind,
    SpecialMarine,
    MarineDenseFog,
    Ashfall,
    MarineDenseSmoke,
    RoughBar,
    RipCurrent,
    SmallCraft,
    HazardousSeas,
    SmallCraftWind,
    DenseSmoke,
    Storm,
    StormSurge,
    HighSurf,
    SevereThunderstorm,
    SmallCraftHazardousSeas,
    Tornado,
    TropicalStorm,
    Tsunami,
    Typhoon,
    FreezingSpray,
    Wind,
    WinterStorm,
    WinterWeather,
    ExtraordinaryHeat,
    FreezingFog,
    FreezingRain,
}

impl FromStr for VtecPhenomenon {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(match s.to_ascii_lowercase().as_str() {
            "aq" => Self::AirQuality,
            "as" => Self::AirStagnation,
            "bh" => Self::BeachHazards,
            "bw" => Self::BriskWind,
            "bz" => Self::Blizzard,
            "cf" => Self::CoastalFlood,
            "cw" => Self::ColdWeather,
            "ds" => Self::DustStorm,
            "du" => Self::BlowingDust,
            "ec" => Self::ExtremeCold,
            "eh" => Self::ExcessiveHeat,
            "ew" => Self::ExcessiveWind,
            "fa" => Self::ArealFlood,
            "ff" => Self::FlashFlood,
            "fg" => Self::DenseFog,
            "fl" => Self::Flood,
            "hy" => Self::Hydrological,
            "fr" => Self::Frost,
            "fw" => Self::FireWeather,
            "rf" => Self::RedFlag,
            "fz" => Self::Freeze,
            "gl" => Self::Gale,
            "hf" => Self::HurricaneForceWind,
            "ht" => Self::Heat,
            "hu" => Self::Hurricane,
            "hw" => Self::HighWind,
            "sq" => Self::SnowSquall,
            "is" => Self::IceStorm,
            "le" => Self::LakeEffectSnow,
            "lo" => Self::LowWater,
            "ls" => Self::LakeshoreFlood,
            "lw" => Self::LakeWind,
            "ma" => Self::SpecialMarine,
            "mf" => Self::MarineDenseFog,
            "mh" => Self::Ashfall,
            "ms" => Self::MarineDenseSmoke,
            "rb" => Self::RoughBar,
            "rp" => Self::RipCurrent,
            "sc" => Self::SmallCraft,
            "se" => Self::HazardousSeas,
            "si" => Self::SmallCraftWind,
            "sm" => Self::DenseSmoke,
            "sr" => Self::Storm,
            "ss" => Self::StormSurge,
            "su" => Self::HighSurf,
            "sv" => Self::SevereThunderstorm,
            "sw" => Self::SmallCraftHazardousSeas,
            "to" => Self::Tornado,
            "tr" => Self::TropicalStorm,
            "ts" => Self::Tsunami,
            "ty" => Self::Typhoon,
            "up" => Self::FreezingSpray,
            "wi" => Self::Wind,
            "ws" => Self::WinterStorm,
            "ww" => Self::WinterWeather,
            "xh" => Self::ExtraordinaryHeat,
            "zf" => Self::FreezingFog,
            "zr" => Self::FreezingRain,

            _ => return Err(()),
        })
    }
}

impl Display for VtecPhenomenon {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

impl VtecPhenomenon {
    #[must_use]
    pub const fn name(&self) -> &'static str {
        match self {
            Self::AirQuality => "Air Quality",
            Self::AirStagnation => "Air Stagnation",
            Self::BeachHazards => "Beach Hazards",
            Self::BriskWind => "Brisk Wind",
            Self::Blizzard => "Blizzard",
            Self::CoastalFlood => "Coastal Flood",
            Self::ColdWeather => "Cold Weather",
            Self::DustStorm => "Dust Storm",
            Self::BlowingDust => "Blowing Dust",
            Self::ExtremeCold => "Extreme Cold",
            Self::ExcessiveHeat => "Excessive Heat",
            Self::ExcessiveWind => "Excessive Wind",
            Self::ArealFlood => "Areal Flood",
            Self::FlashFlood => "Flash Flood",
            Self::DenseFog => "Dense Fog",
            Self::Flood => "Flood",
            Self::Hydrological => "Hydrological",
            Self::Frost => "Frost",
            Self::FireWeather => "Fire Weather",
            Self::RedFlag => "Red Flag",
            Self::Freeze => "Freeze",
            Self::Gale => "Gale",
            Self::HurricaneForceWind => "Hurricane Force Wind",
            Self::Heat => "Heat",
            Self::Hurricane => "Hurricane",
            Self::HighWind => "High Wind",
            Self::SnowSquall => "Snow Squall",
            Self::IceStorm => "Ice Storm",
            Self::LakeEffectSnow => "Lake Effect Snow",
            Self::LowWater => "Low Water",
            Self::LakeshoreFlood => "Lakeshore Flood",
            Self::LakeWind => "Lake Wind",
            Self::SpecialMarine => "Special Marine",
            Self::MarineDenseFog => "Dense Fog (Marine)",
            Self::Ashfall => "Ashfall",
            Self::MarineDenseSmoke => "Dense Smoke (Marine)",
            Self::RoughBar => "Small Craft Advisory for Rough Bar",
            Self::RipCurrent => "High Rip Current Risk",
            Self::SmallCraft => "Small Craft",
            Self::HazardousSeas => "Hazardous Seas",
            Self::SmallCraftWind => "Small Craft Advisory for Winds",
            Self::DenseSmoke => "Dense Smoke",
            Self::Storm => "Storm",
            Self::StormSurge => "Storm Surge",
            Self::HighSurf => "High Surf",
            Self::SevereThunderstorm => "Severe Thunderstorm",
            Self::SmallCraftHazardousSeas => "Small Craft Advisory for Hazardous Seas",
            Self::Tornado => "Tornado",
            Self::TropicalStorm => "Tropical Storm",
            Self::Tsunami => "Tsunami",
            Self::Typhoon => "Typhoon",
            Self::FreezingSpray => "Freezing Spray",
            Self::Wind => "Wind",
            Self::WinterStorm => "Winter Storm",
            Self::WinterWeather => "Winter Weather",
            Self::ExtraordinaryHeat => "Extreme Heat",
            Self::FreezingFog => "Freezing Fog",
            Self::FreezingRain => "Freezing Rain",
        }
    }

    #[must_use]
    pub fn description(&self, significance: VtecSignificance) -> String {
        format!("{} {}", self.name(), significance)
    }

    #[must_use]
    pub const fn get_color(&self, significance: VtecSignificance) -> Option<(u8, u8, u8)> {
        Some(match (self, significance) {
            (Self::AirQuality, VtecSignificance::Advisory) => (128, 128, 128),
            (Self::AirStagnation, VtecSignificance::Outlook) => (128, 128, 128),
            (Self::AirStagnation, VtecSignificance::Advisory) => (128, 128, 128),
            (Self::BeachHazards, VtecSignificance::Statement) => (64, 224, 208),
            (Self::BriskWind, VtecSignificance::Advisory) => (216, 191, 216),
            (Self::Blizzard, VtecSignificance::Watch) => (173, 255, 47),
            (Self::Blizzard, VtecSignificance::Warning) => (255, 69, 0),
            (Self::CoastalFlood, VtecSignificance::Watch) => (102, 205, 170),
            (Self::CoastalFlood, VtecSignificance::Warning) => (34, 139, 34),
            (Self::CoastalFlood, VtecSignificance::Advisory) => (124, 252, 0),
            (Self::CoastalFlood, VtecSignificance::Statement) => (107, 142, 35),
            (Self::ColdWeather, VtecSignificance::Advisory) => (175, 238, 238),
            (Self::DustStorm, VtecSignificance::Warning) => (255, 228, 196),
            (Self::DustStorm, VtecSignificance::Advisory) => (189, 183, 107),
            (Self::BlowingDust, VtecSignificance::Advisory) => (189, 183, 107),
            (Self::ExtremeCold, VtecSignificance::Watch) => (0, 0, 255),
            (Self::ExtremeCold, VtecSignificance::Warning) => (0, 0, 255),
            (Self::ExcessiveHeat, VtecSignificance::Watch) => (128, 0, 0),
            (Self::ExcessiveHeat, VtecSignificance::Warning) => (199, 21, 133),
            (Self::ExcessiveWind, VtecSignificance::Warning) => (255, 20, 147),
            (Self::ArealFlood, VtecSignificance::Watch) => (46, 139, 87),
            (Self::ArealFlood, VtecSignificance::Warning) => (46, 139, 87),
            (Self::ArealFlood, VtecSignificance::Advisory) => (46, 139, 87),
            (Self::FlashFlood, VtecSignificance::Watch) => (50, 205, 50),
            (Self::FlashFlood, VtecSignificance::Statement) => (154, 205, 50),
            (Self::FlashFlood, VtecSignificance::Warning) => (139, 0, 0),
            (Self::DenseFog, VtecSignificance::Advisory) => (112, 128, 144),
            (Self::Flood, VtecSignificance::Watch) => (46, 139, 87),
            (Self::Flood, VtecSignificance::Warning) => (0, 128, 0),
            (Self::Hydrological, VtecSignificance::Statement) => (0, 255, 127),
            (Self::Flood, VtecSignificance::Statement) => (0, 255, 127),
            (Self::Flood, VtecSignificance::Advisory) => (0, 255, 127),
            (Self::Frost, VtecSignificance::Advisory) => (100, 149, 237),
            (Self::FireWeather, VtecSignificance::Watch) => (255, 222, 173),
            (Self::Frost, VtecSignificance::Warning) => (255, 20, 147),
            (Self::FireWeather, VtecSignificance::Warning) => (255, 20, 147),
            (Self::RedFlag, VtecSignificance::Warning) => (255, 20, 147),
            (Self::Freeze, VtecSignificance::Watch) => (65, 105, 225),
            (Self::Freeze, VtecSignificance::Warning) => (0, 255, 255),
            (Self::Gale, VtecSignificance::Watch) => (255, 192, 203),
            (Self::Gale, VtecSignificance::Warning) => (221, 160, 221),
            (Self::HurricaneForceWind, VtecSignificance::Watch) => (153, 50, 204),
            (Self::HurricaneForceWind, VtecSignificance::Warning) => (205, 92, 92),
            (Self::Heat, VtecSignificance::Advisory) => (255, 127, 78),
            (Self::Hurricane, VtecSignificance::Watch) => (255, 0, 255),
            (Self::Hurricane, VtecSignificance::Statement) => (255, 255, 0),
            (Self::Hurricane, VtecSignificance::Warning) => (220, 20, 60),
            (Self::HighWind, VtecSignificance::Watch) => (184, 134, 11),
            (Self::HighWind, VtecSignificance::Warning) => (218, 165, 32),
            (Self::SnowSquall, VtecSignificance::Warning) => (239, 43, 28),
            (Self::IceStorm, VtecSignificance::Warning) => (139, 0, 139),
            (Self::LakeEffectSnow, VtecSignificance::Watch) => (135, 206, 250),
            (Self::LakeEffectSnow, VtecSignificance::Warning) => (0, 139, 139),
            (Self::LakeEffectSnow, VtecSignificance::Advisory) => (72, 209, 204),
            (Self::LowWater, VtecSignificance::Advisory) => (128, 0, 0),
            (Self::LakeshoreFlood, VtecSignificance::Watch) => (102, 205, 170),
            (Self::LakeshoreFlood, VtecSignificance::Statement) => (124, 252, 0),
            (Self::LakeshoreFlood, VtecSignificance::Warning) => (34, 139, 34),
            (Self::LakeshoreFlood, VtecSignificance::Advisory) => (124, 252, 0),
            (Self::LakeWind, VtecSignificance::Advisory) => (210, 180, 140),
            (Self::SpecialMarine, VtecSignificance::Watch) => (255, 218, 185),
            (Self::SpecialMarine, VtecSignificance::Statement) => (255, 218, 185),
            (Self::SpecialMarine, VtecSignificance::Warning) => (219, 112, 147),
            (Self::MarineDenseFog, VtecSignificance::Advisory) => (112, 128, 144),
            (Self::Ashfall, VtecSignificance::Warning) => (169, 169, 169),
            (Self::Ashfall, VtecSignificance::Advisory) => (105, 105, 105),
            (Self::MarineDenseSmoke, VtecSignificance::Advisory) => (240, 230, 140),
            (Self::RoughBar, VtecSignificance::Advisory) => (216, 191, 216),
            (Self::RipCurrent, VtecSignificance::Statement) => (64, 224, 208),
            (Self::SmallCraft, VtecSignificance::Advisory) => (216, 191, 216),
            (Self::HazardousSeas, VtecSignificance::Watch) => (72, 61, 139),
            (Self::HazardousSeas, VtecSignificance::Warning) => (216, 191, 216),
            (Self::SmallCraftWind, VtecSignificance::Advisory) => (216, 191, 216),
            (Self::DenseSmoke, VtecSignificance::Advisory) => (240, 230, 140),
            (Self::Storm, VtecSignificance::Watch) => (238, 130, 238),
            (Self::Storm, VtecSignificance::Warning) => (153, 50, 204),
            (Self::StormSurge, VtecSignificance::Watch) => (219, 127, 247),
            (Self::StormSurge, VtecSignificance::Warning) => (181, 36, 247),
            (Self::HighSurf, VtecSignificance::Warning) => (34, 139, 34),
            (Self::HighSurf, VtecSignificance::Advisory) => (186, 85, 211),
            (Self::SevereThunderstorm, VtecSignificance::Watch) => (219, 112, 147),
            (Self::SevereThunderstorm, VtecSignificance::Statement) => (0, 255, 255),
            (Self::SevereThunderstorm, VtecSignificance::Warning) => (255, 165, 0),
            (Self::SmallCraftHazardousSeas, VtecSignificance::Advisory) => (216, 191, 216),
            (Self::Tornado, VtecSignificance::Watch) => (255, 255, 0),
            (Self::Tornado, VtecSignificance::Warning) => (255, 0, 0),
            (Self::TropicalStorm, VtecSignificance::Watch) => (240, 128, 128),
            (Self::TropicalStorm, VtecSignificance::Warning) => (178, 34, 34),
            (Self::Tsunami, VtecSignificance::Watch) => (255, 0, 255),
            (Self::Tsunami, VtecSignificance::Warning) => (253, 99, 71),
            (Self::Tsunami, VtecSignificance::Advisory) => (210, 105, 30),
            (Self::Typhoon, VtecSignificance::Watch) => (255, 0, 255),
            (Self::Typhoon, VtecSignificance::Warning) => (253, 99, 71),
            (Self::FreezingSpray, VtecSignificance::Watch) => (188, 143, 143),
            (Self::FreezingSpray, VtecSignificance::Warning) => (0, 192, 255),
            (Self::FreezingSpray, VtecSignificance::Advisory) => (0, 192, 255),
            (Self::Wind, VtecSignificance::Advisory) => (210, 180, 140),
            (Self::WinterStorm, VtecSignificance::Watch) => (70, 130, 180),
            (Self::WinterStorm, VtecSignificance::Warning) => (255, 105, 180),
            (Self::WinterWeather, VtecSignificance::Advisory) => (123, 104, 238),
            (Self::ExtraordinaryHeat, VtecSignificance::Watch) => (128, 0, 0),
            (Self::ExtraordinaryHeat, VtecSignificance::Warning) => (199, 21, 133),
            (Self::FreezingFog, VtecSignificance::Advisory) => (0, 128, 128),
            (Self::FreezingRain, VtecSignificance::Advisory) => (218, 112, 214),

            _ => return None,
        })
    }

    #[must_use]
    pub const fn code(&self) -> &'static str {
        match self {
            Self::AirQuality => "aq",
            Self::AirStagnation => "as",
            Self::BeachHazards => "bh",
            Self::BriskWind => "bw",
            Self::Blizzard => "bz",
            Self::CoastalFlood => "cf",
            Self::ColdWeather => "cw",
            Self::DustStorm => "ds",
            Self::BlowingDust => "du",
            Self::ExtremeCold => "ec",
            Self::ExcessiveHeat => "eh",
            Self::ExcessiveWind => "ew",
            Self::ArealFlood => "fa",
            Self::FlashFlood => "ff",
            Self::DenseFog => "fg",
            Self::Flood => "fl",
            Self::Hydrological => "hy",
            Self::Frost => "fr",
            Self::FireWeather => "fw",
            Self::RedFlag => "rf",
            Self::Freeze => "fz",
            Self::Gale => "gl",
            Self::HurricaneForceWind => "hf",
            Self::Heat => "ht",
            Self::Hurricane => "hu",
            Self::HighWind => "hw",
            Self::SnowSquall => "sq",
            Self::IceStorm => "is",
            Self::LakeEffectSnow => "le",
            Self::LowWater => "lo",
            Self::LakeshoreFlood => "ls",
            Self::LakeWind => "lw",
            Self::SpecialMarine => "ma",
            Self::MarineDenseFog => "mf",
            Self::Ashfall => "mh",
            Self::MarineDenseSmoke => "ms",
            Self::RoughBar => "rb",
            Self::RipCurrent => "rp",
            Self::SmallCraft => "sc",
            Self::HazardousSeas => "se",
            Self::SmallCraftWind => "si",
            Self::DenseSmoke => "sm",
            Self::Storm => "sr",
            Self::StormSurge => "ss",
            Self::HighSurf => "su",
            Self::SevereThunderstorm => "sv",
            Self::SmallCraftHazardousSeas => "sw",
            Self::Tornado => "to",
            Self::TropicalStorm => "tr",
            Self::Tsunami => "ts",
            Self::Typhoon => "ty",
            Self::FreezingSpray => "up",
            Self::Wind => "wi",
            Self::WinterStorm => "ws",
            Self::WinterWeather => "ww",
            Self::ExtraordinaryHeat => "xh",
            Self::FreezingFog => "zf",
            Self::FreezingRain => "zr",
        }
    }
}
